version: "3.8"

services:
  postgres:
    image: "postgres:10"
    restart: always
    container_name: "java-db"
    environment:
      - POSTGRES_USER=yadoa_app
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=yadoa
    ports:
      - "5432:5432"
  app:
    depends_on:
      - postgres
    build: ./
    restart: always
    container_name: "java-app"
    ports:
      - "80:8080"
    volumes:
      - .m2:/root/.m2

volumes:
  db:
  # mycustom.cnf: