version: "3.8"

services:
  postgres:
    image: "postgres:10"
    restart: always
    env_file: ./.env
    container_name: "java-db"
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=$POSTGRES_DB
    ports:
      - $POSTGRES_LOCAL_PORT:$POSTGRES_DOCKER_PORT
  app:
    depends_on:
      - postgres
    build: ./
    restart: always
    env_file: ./.env
    container_name: "java-app"
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:postgresql://postgres:$POSTGRES_DOCKER_PORT/$POSTGRES_DB",
        "spring.datasource.username" : "$POSTGRES_USER",
        "spring.datasource.password" : "", 
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.PostgreSQLDialect",
        "spring.jpa.hibernate.ddl-auto" : "none",
        "spring.sql.init.mode" : "always",
        "spring.datasource.driver-class-name" : "org.postgresql.Driver"
      }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  db:
  # mycustom.cnf: