version: "3.8"

services:
  postgres:
    image: "postgres:10"
    restart: always
    env_file: .env
    container_name: "java-db"
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=$POSTGRES_DB
    ports:
      - $POSTGRES_LOCAL_PORT:$POSTGRES_DOCKER_PORT
  app:
    depends_on:
      - postgres
    build: ./
    restart: always
    env_file: .env
    container_name: "java-app"
    ports:
      - "80:8080"
    volumes:
      - .m2:/root/.m2

volumes:
  db:
  # mycustom.cnf: